In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(1, 10, dtype='float64')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
list2d = [[1,2,3],[4,5,6]]
arr2d = np.array(list2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
list2d = [[1,2,3],[4,5,6]]
arr2d = np.array(list2d)
print(arr2d.shape)

(2, 3)


In [10]:
arr = np.array([1,2,3,4,5])
print(np.max(arr))

5


In [11]:
first = [1, 2, 3]
second = [10, 20, 30]
third = [100, 200, 300]
numpy_array = np.array([first, second, third])
print(numpy_array)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [12]:
print(np.max(numpy_array, axis=1))

[  3  30 300]


In [13]:
print(np.max(numpy_array, axis=0))

[100 200 300]


In [14]:
arr = np.random.randint(10, size=(4,2))
print(arr)

[[4 8]
 [7 5]
 [5 1]
 [0 2]]


In [15]:
new_arr = arr.reshape(2,4)
print(new_arr )

[[4 8 7 5]
 [5 1 0 2]]
